/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class platforms_x86_X86_DVFS */

#ifndef _Included_platforms_x86_X86_DVFS
#define _Included_platforms_x86_X86_DVFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    getTransitionLatency
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_platforms_x86_X86_1DVFS_getTransitionLatency
  (JNIEnv *, jobject, jint);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    getHardwareLimits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_platforms_x86_X86_1DVFS_getHardwareLimits
  (JNIEnv *, jobject, jint);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    getGovernor
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_platforms_x86_X86_1DVFS_getGovernor
  (JNIEnv *, jobject, jint);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    getAvailableGovernors
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_platforms_x86_X86_1DVFS_getAvailableGovernors
  (JNIEnv *, jobject, jint);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    setGovernor
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_platforms_x86_X86_1DVFS_setGovernor
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    getFrequency
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_platforms_x86_X86_1DVFS_getFrequency
  (JNIEnv *, jobject, jint);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    getAvailableFrequencies
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_platforms_x86_X86_1DVFS_getAvailableFrequencies
  (JNIEnv *, jobject, jint);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    setFrequency
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_platforms_x86_X86_1DVFS_setFrequency
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    setFreqPolicy
 * Signature: (IJJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_platforms_x86_X86_1DVFS_setFreqPolicy
  (JNIEnv *, jobject, jint, jlong, jlong, jstring);

/*
 * Class:     platforms_x86_X86_DVFS
 * Method:    getFreqStats
 * Signature: (I)Lplatforms/x86/FreqStats;
 */
JNIEXPORT jobject JNICALL Java_platforms_x86_X86_1DVFS_getFreqStats
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
