/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SCC */

#ifndef _Included_SCC
#define _Included_SCC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SCC
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_init
  (JNIEnv *, jobject);

/*
 * Class:     SCC
 * Method:    terminate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_terminate
  (JNIEnv *, jobject);

/*
 * Class:     SCC
 * Method:    getTileSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_getTileSize
  (JNIEnv *, jobject);

/*
 * Class:     SCC
 * Method:    getNodeRank
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_getNodeRank
  (JNIEnv *, jobject);

/*
 * Class:     SCC
 * Method:    getTileInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_getTileInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
