/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SCC_DVFS */

#ifndef _Included_SCC_DVFS
#define _Included_SCC_DVFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SCC_DVFS
 * Method:    getPowerDomain
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_DVFS_getPowerDomain
  (JNIEnv *, jobject);

/*
 * Class:     SCC_DVFS
 * Method:    getPowerDomainMaster
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_DVFS_getPowerDomainMaster
  (JNIEnv *, jobject);

/*
 * Class:     SCC_DVFS
 * Method:    getPowerDomainSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_DVFS_getPowerDomainSize
  (JNIEnv *, jobject);

/*
 * Class:     SCC_DVFS
 * Method:    setPower
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_SCC_DVFS_setPower
  (JNIEnv *, jobject, jint);

/*
 * Class:     SCC_DVFS
 * Method:    waitPower
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SCC_DVFS_waitPower
  (JNIEnv *, jobject);

/*
 * Class:     SCC_DVFS
 * Method:    setFrequencyDivider
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SCC_DVFS_setFrequencyDivider
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
